window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  #  opacity: 0.90
  # Let windows manager assign the termial size
  dimensions:
    columns: 120
    lines: 40
  decorations: full
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3


font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: MediumItalic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: BoldItalic
  size: 13
draw_bold_text_with_bright_colors: true

# Color theme
import:
  #- ~/.config/alacritty/themes/tokyo-night.yaml
- ~/.config/alacritty/themes/dracula.yaml

selection:
  save_to_clipboard: false

shell:
  program: /usr/local/bin/fish
  args:
    - --login

# MACOS - Super == Command
key_bindings:
  - {key: F, mods: Super|Shift, action: ToggleFullscreen}
  - {key: N, mods: Command, action: CreateNewWindow}

